# Generated by Django 2.1.7 on 2019-08-05 06:55

from django.db import migrations, models
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeaccount',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='typeaccount',
            name='code',
            field=models.CharField(default=master.models.docNumTypeAccount, editable=False, max_length=150, null=True, verbose_name='Document Number'),
        ),
    ]
