# Generated by Django 2.1.7 on 2019-08-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20190805_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeaccount',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
