# Generated by Django 2.1.7 on 2019-08-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_typeaccount_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create Date'),
        ),
    ]
