# Generated by Django 2.1.7 on 2019-08-05 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0004_typeaccount_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update'),
        ),
        migrations.AddField(
            model_name='typeaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
