# Generated by Django 2.1.7 on 2019-08-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20190805_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeaccount',
            name='status',
            field=models.CharField(choices=[('A', 'Aktif'), ('T', 'Tidak Aktif')], max_length=10, null=True, verbose_name='Status'),
        ),
    ]
